title: Preet Mehta
description: Data Engineering, Healthcare Analytics and AI/ML
url: https://ynpreet.github.io
baseurl: ""
markdown: kramdown
permalink: /writing/:title/
exclude:
  - Readme.txt
  - changelog.txt
